name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install modules
        run: npm ci

      - name: Build
        run: npm run build

      - name: Install example modules
        working-directory: ./example
        run: npm ci

      - name: Eslint
        run: npm run lint

      - name: Tests
        run: npm run test
