name: Publish

on:
  release:
    types: [ created ]

jobs:
  build-workflow:
    uses: ./.github/workflows/build.yml

  publish:
    runs-on: ubuntu-latest
    needs: [ build-workflow ]

    steps:
      - name: Setup
        uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: Publish base package
        run: |
          cd packages/rawmask
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Publish react package
        run: |
          cd packages/react-rawmask
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}


